# Generated by Django 2.1.2 on 2023-05-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230513_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='url'),
        ),
    ]
