# Generated by Django 2.1.2 on 2023-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subscriber_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='subscriber_count'),
        ),
    ]
