# Generated by Django 2.1.2 on 2023-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230529_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recently_upload_video_id',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='recently_upload_video_id'),
        ),
        migrations.AddField(
            model_name='item',
            name='recently_upload_video_published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='recently_upload_video_published_at'),
        ),
        migrations.AddField(
            model_name='item',
            name='recently_upload_video_title',
            field=models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='recently_upload_video_title'),
        ),
        migrations.AddField(
            model_name='item',
            name='recently_upload_video_tumbnail',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True, verbose_name='recently_upload_video_tumbnail'),
        ),
        migrations.AddField(
            model_name='item',
            name='recently_upload_video_tumbnail_height',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='recently_upload_video_tumbnail_height'),
        ),
        migrations.AddField(
            model_name='item',
            name='recently_upload_video_tumbnail_width',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='recently_upload_video_tumbnail_width'),
        ),
        migrations.AddField(
            model_name='item',
            name='uploads_playlist_id',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='uploads_playlist_id'),
        ),
    ]
