# Generated by Django 2.1.2 on 2023-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230601_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recently_upload_video_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='recently_upload_video_id'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recently_upload_video_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='recently_upload_video_title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recently_upload_video_tumbnail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='recently_upload_video_tumbnail'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recently_upload_video_tumbnail_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='recently_upload_video_tumbnail_height'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recently_upload_video_tumbnail_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='recently_upload_video_tumbnail_width'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uploads_playlist_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='uploads_playlist_id'),
        ),
    ]
