# Generated by Django 2.1.2 on 2023-06-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230602_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='channelTitle',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='url',
            new_name='channelUrl',
        ),
    ]
