# Generated by Django 2.1.2 on 2023-06-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230602_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='channelTitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='channelTitle'),
        ),
    ]
