# Generated by Django 2.1.2 on 2023-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230602_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='channelId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='channelTitle',
        ),
        migrations.RemoveField(
            model_name='item',
            name='channelUrl',
        ),
        migrations.AddField(
            model_name='item',
            name='channel_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='channel_id'),
        ),
        migrations.AddField(
            model_name='item',
            name='channel_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='チャンネル名'),
        ),
        migrations.AddField(
            model_name='item',
            name='channel_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='channelUrl'),
        ),
    ]
