# Generated by Django 2.1.2 on 2023-06-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230602_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='channel_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='channel_url'),
        ),
    ]
